ERROR - 2022-02-19 10:43:34 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-02-19 10:43:34 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp\htdocs\WEB\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\WEB\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\WEB\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\WEB\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 C:\xampp\htdocs\WEB\app\Controllers\LoginController.php(24): CodeIgniter\BaseModel->first()
#5 C:\xampp\htdocs\WEB\system\CodeIgniter.php(825): App\Controllers\LoginController->auth()
#6 C:\xampp\htdocs\WEB\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#7 C:\xampp\htdocs\WEB\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\WEB\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\WEB\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-02-19 21:24:36 --> Use of undefined constant auth - assumed 'auth' (this will throw an Error in a future version of PHP)
#0 C:\xampp\htdocs\WEB\system\CodeIgniter.php(802): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Use of undefine...', 'C:\\xampp\\htdocs...', 802, Array)
#1 C:\xampp\htdocs\WEB\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->createController()
#2 C:\xampp\htdocs\WEB\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\WEB\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\WEB\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-02-19 21:24:54 --> Use of undefined constant auth - assumed 'auth' (this will throw an Error in a future version of PHP)
#0 C:\xampp\htdocs\WEB\system\CodeIgniter.php(802): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Use of undefine...', 'C:\\xampp\\htdocs...', 802, Array)
#1 C:\xampp\htdocs\WEB\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->createController()
#2 C:\xampp\htdocs\WEB\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\WEB\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\WEB\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-02-19 21:24:55 --> Use of undefined constant auth - assumed 'auth' (this will throw an Error in a future version of PHP)
#0 C:\xampp\htdocs\WEB\system\CodeIgniter.php(802): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Use of undefine...', 'C:\\xampp\\htdocs...', 802, Array)
#1 C:\xampp\htdocs\WEB\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->createController()
#2 C:\xampp\htdocs\WEB\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\WEB\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\WEB\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-02-19 21:25:16 --> Use of undefined constant Auth - assumed 'Auth' (this will throw an Error in a future version of PHP)
#0 C:\xampp\htdocs\WEB\system\CodeIgniter.php(802): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Use of undefine...', 'C:\\xampp\\htdocs...', 802, Array)
#1 C:\xampp\htdocs\WEB\system\CodeIgniter.php(403): CodeIgniter\CodeIgniter->createController()
#2 C:\xampp\htdocs\WEB\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\WEB\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\WEB\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-02-19 21:36:34 --> Call to undefined function user()
#0 C:\xampp\htdocs\WEB\system\View\View.php(210): include()
#1 C:\xampp\htdocs\WEB\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\htdocs\WEB\system\View\View.php(424): CodeIgniter\View\View->render('templates/topba...', NULL, true)
#3 C:\xampp\htdocs\WEB\app\Views\templates\index.php(44): CodeIgniter\View\View->include('templates/topba...')
#4 C:\xampp\htdocs\WEB\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\WEB\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\WEB\system\View\View.php(226): CodeIgniter\View\View->render('templates/index', Array, true)
#7 C:\xampp\htdocs\WEB\system\Common.php(1089): CodeIgniter\View\View->render('user/index', Array, true)
#8 C:\xampp\htdocs\WEB\app\Controllers\LoginController.php(15): view('user/index')
#9 C:\xampp\htdocs\WEB\system\CodeIgniter.php(825): App\Controllers\LoginController->user()
#10 C:\xampp\htdocs\WEB\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#11 C:\xampp\htdocs\WEB\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\WEB\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\WEB\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#14 {main}
